hydra:
  run:
    dir: ./outputs/${rundir}
seed: 42
data: ???
targets_prefix: aid_
rundir: ???
num_classes: 235 
train_split: 0.9
device: "cuda:0"
batch_size: 256
net:
  gattn_emb: 32
  gattn_heads: 16
  final_emb: 2048
  dropout: 0.3
train:
  # Optimizer: AdamW or LambW
  optim: AdamW
  batch_size: 256
  epochs: 30
  metric_freq: 200
  start_swa: 20
  n_swa: 10
  keep_swa: 10
  lr: 1e-3
  pos_class_weight: 8.0
  wd:
    pre_cycle: 2e-2
    post_cycle: 2e-2
  cycle:
    enabled: No
    base_lr: 1e-3
    max_lr: 1e-2
    momentum: No
    epochs_up: 15
    epochs_down: 15
